// Generated by Xata Codegen 0.30.0. Please do not edit.
import { buildClient } from "@xata.io/client";
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from "@xata.io/client";
import dotenv from "dotenv";
dotenv.config();

const tables = [
  {
    name: "ai",
    checkConstraints: {
      ai_xata_id_length_xata_id: {
        name: "ai_xata_id_length_xata_id",
        columns: ["xata_id"],
        definition: "CHECK ((length(xata_id) < 256))",
      },
      ai_xata_string_length_contents: {
        name: "ai_xata_string_length_contents",
        columns: ["contents"],
        definition: "CHECK ((length(contents) <= 2048))",
      },
      ai_xata_vector_length_embedding: {
        name: "ai_xata_vector_length_embedding",
        columns: ["embedding"],
        definition: "CHECK ((array_length(embedding, 1) = 1536))",
      },
    },
    foreignKeys: {},
    primaryKey: [],
    uniqueConstraints: {
      _pgroll_new_ai_xata_id_key: {
        name: "_pgroll_new_ai_xata_id_key",
        columns: ["xata_id"],
      },
    },
    columns: [
      {
        name: "contents",
        type: "string",
        notNull: false,
        unique: false,
        defaultValue: null,
        comment: '{"xata.type":"string"}',
      },
      {
        name: "embedding",
        type: "vector",
        notNull: false,
        unique: false,
        defaultValue: null,
        comment: '{"xata.search.dimension":1536}',
      },
      {
        name: "xata_createdat",
        type: "datetime",
        notNull: true,
        unique: false,
        defaultValue: "now()",
        comment: "",
      },
      {
        name: "xata_id",
        type: "text",
        notNull: true,
        unique: true,
        defaultValue: "('rec_'::text || (xata_private.xid())::text)",
        comment: "",
      },
      {
        name: "xata_updatedat",
        type: "datetime",
        notNull: true,
        unique: false,
        defaultValue: "now()",
        comment: "",
      },
      {
        name: "xata_version",
        type: "int",
        notNull: true,
        unique: false,
        defaultValue: "0",
        comment: "",
      },
    ],
  },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type Ai = InferredTypes["ai"];
export type AiRecord = Ai & XataRecord;

export type DatabaseSchema = {
  ai: AiRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL: process.env.XATA_URL,
  apiKey: process.env.XATA_API_KEY,
  branch: process.env.XATA_BRANCH,
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
